### ISSUE TITLE
Numbering of Examples

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#40]
In CSD the Examples provided inside lists are not following the overall numbering of examples within the same clause.

**Comment by opoudjis** [comment]
Issue related to https://github.com/riboseinc/metanorma-csd/issues/36, though I'm less sanguine about fixing it here.

Termexamples, like Termnotes, currently assume that they will be at only one level of nesting below the term. And normally they are.

The problem in the CSD document you have provided is that you have an extensive preamble to the symbols section, clearly intended as a subclause. But there is no provision for that in the grammar: it assumes this is a terms subclause, and there is no provision in terms subclauses for prefatory material, so 3.2.1 General is treated as a term being defined.

I'll allow arbitrary nesting of term examples, which will address this issue, but that's not the fix. The fix is to somehow flag introductory clauses in term subclauses, something we currently don't recognise. Presumably something like `[.nonterm]` as an attribute of the header. We'd also have to modify the grammar, to permit introductory sections to any term clause; and this would presumably apply to ISO as well.

**Comment by opoudjis** [comment]
We can put in General sections, prefixed with `[.nonterm]`; we can continue to have them flagged as a syntax error, and maybe mention to ISO that they have an issue—if they are already inserting such prefatory text.

**Comment by opoudjis** [comment]
Introduced nonterm in metanorma-standoc; documented in metanorma-iso docs
