### ISSUE TITLE
RFC citations should not render edition year (and the edition year is wrong anyhow)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#43]
Citation of `<<RFC5545>>` with the following bibliography gives out `RFC 5545:2018` (which is obviously wrong).

```
[bibliography]
== Bibliography

* [[[RFC5545,IETF RFC 5545]]], _AUTOFILL_
```

**Comment by opoudjis** [comment]
Idiosyncratic rendering of citations from different sources are not a feature.

The rule being applied consistently for citations is, if there is a year of publication in the ISOXML reference, it will show up in the citation; and I'm not sure that's wrong; why should years show up in ISO citations and not RFC citations? 

If we want to suppress years from showing up in RFC citations, we can just block publication dates from the citations returned by rfcbib. But that's a distortion of the citation. The alternate really is to strip years if the citation happens to be an IETF citation. I can do that, but I think it's a bad idea.

The year of publication being wrong, that's a separate issue. It turns out it's rfcbib naively assuming the RFC dates are YYYY-MM-DD, when they are in fact YYYY-month (`2009-September`). Will fix that, that's a clear bug. Please advise what to do with RFC dates.

**Comment by ronaldtse** [comment]
1. So in non IETF documents, RFCs should be cited as “IETF RFC XXXX”. 

2. RFCs don’t cite with dates because each RFCs number can only occur once, not unchanged according to editions. I wouldn’t call this “idiocyncratic” in terms of citations but in the original naming of them. And that should be supported?

3. Prefix suppression of RFCs (the “IETF “ prefix) perhaps should be the feature supported within IETF documents?

**Comment by opoudjis** [comment]
Prefix suppression of GB Standard is already supported within GB documents, and the same will happen if and when asciidoctor-rfc uses rfcbib.

**Comment by opoudjis** [comment]
This is revealing that the modelling of document identifiers for standards is wrong. 

The last fix to the iso-bib-item modelling of citations was to establish that the publisher prefix is part of the document identifier: the identifier is not "1234", to which "ISO/IEC" is prefixed, but "ISO/IEC 1234". This allows iso-bib-item to be used for other standards, like IETF I.D., where the prefix is not a publisher abbreviation. The assumption that the prefixes indicate publishing agencies is specific to ISO, and does not apply to IETF standards.

We have the same issue here. The assumption that the year is added to the document identifier in citing them is wrong: the year is part of the document identifier. This helps with the fact that in GB standards, the year is separated from the document number by a dash and not a colon. It also means that we do not need to build exceptions in to citations of different classes of standard: the citation is always just the document identifier, and the choice of whether the year is included in the document identifier or not is specific to each class of identifier.

Please confirm that you're ok to proceed on this basis, because this will mean another set of changes to isobib, gbbib, and isodoc.

**Comment by ronaldtse** [comment]
I think it is correct that each publisher may cite according to different styles. 

For example, in IETF documents, “RFCs” are cited as “RFC XXXX”. In ISO (and other) documents, RFCs are cited as “IETF RFC XXXX”. 

While in ISO documents, ISO documents are cited as “ISO XXXX”, but in other organization they are also cited identically. 

The document identifier will work except for “all parts”. 

Notice that in some cases, such as dual-logo documents, the document identifier may be different with published by different publishers.

**Comment by opoudjis** [comment]
Drastic change to gbbib and isobib: replacing struct `{ project_number, part_number, prefix: nil }` with `IsoBibItem::DocumentIdentifier`, which has just ID and type. The id will include the year, if applicable, and the delimiter separating the id from the year, which is specific to the standard (colon for ISO, dash for GB).
