### ISSUE TITLE
Missing ToC entry for 3.2 Abbreviations?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#44]
A picture is worth a thousand words.

![screen shot 2018-09-01 at 12 18 39 am](https://user-images.githubusercontent.com/11865/44924048-acb6a100-ad7c-11e8-9808-0bedc042f620.png)

**Comment by opoudjis** [comment]
The abbreviations are not showing up in the ToC, because the parser thinks 3.2 Abbreviations is a Term.

The parser thinks 3.2 Abbreviations is a term, because it has been told that the only permissible "definitions" titles are "Symbols and abbreviated terms"

Against my preference, I'm introducing the variant titles "Symbols", "Abbreviated terms", and "Abbreviations" as permissible Definitions section titles. The proper way to do this, if there  will be further variation, is with an attribute `[heading=symbols and abbreviated terms]`, which overrides whatever is in the title.

**Comment by opoudjis** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/1911039/44941924-53855680-adea-11e8-87c1-316c69d52e82.png">

The rendering continues to impose the canonical titles "Symbols and Abbreviated Terms" and "Terms, definitions, symbols and abbreviated terms", regardless of what has been entered. I encourage you not to make me fix this. (In fact, the grammar currently has no provision for titles of Definitions sections, because that is expected to be a canonical rendering choice and not user-configured.)

Fixed in metanorma-standoc
