### ISSUE TITLE
Create new document type “advisory”

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#59]
The “advisory” doctype will be used to publish press release style documents. 

It should relax the requirements of the T&D and norm refs sections.

**Comment by opoudjis** [comment]
I'm making up my own suffix for these, `Adv`. 

The insistence on T&D and Normative References and their sequencing is specific to ISO (and GB, which inherits from ISO). Since metanorma-standoc has been refactored out, none of the other gems inherit that constraint any more; and indeed, nor should they.

If you *do* want to impose a sequencing or mandatory constraint for clause types in any standard other than ISO or GB, you will need to request it explicitly.

**Comment by opoudjis** [comment]
CSD still complains, through the RNG grammar, that there is no bibliography if I leave it out. I can't leave out an element depending on an attribute, since it is a context-free grammar: if we want warnings for omitting bibliographies for some document types and not others, that will need to be done in code, and you will need to let me know which document types can leave out bibliographies. You will then need to do that for all the standards you are getting me to maintain.

Or, you know. You could just leave it alone, since it is just a warning, and the user is supposed to know what they're doing.

The numbering of sections is not impacted by leaving out terms and normative references, since this gem no longer inherits from ISO (and I stopped ISO doing that anyway).

So I don't think I need to do anything else here. Please confirm.

**Comment by ronaldtse** [comment]
Regarding the bibliography warning, it is fine, it’s still a good reminder for the author if there is anything cited.
