### ISSUE TITLE
Reference to an annex section gets rendered as "Appendix X.Y", not "Annex X.Y"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#73]
A reference to an annex section gets rendered as "Appendix X.Y", not "Annex X.Y".

```adoc
[appendix,obligation="normative"]
= Annex A

== General

[[annex-a-general-note]]
NOTE: blah

== Blah

(see <<annex-a-general-note>>) (<== this one)
```

![screen shot 2019-01-16 at 10 33 09 pm](https://user-images.githubusercontent.com/11865/51255705-b7499e00-19de-11e9-8f1c-0b152d639cb4.png)

**Comment by ronaldtse** [comment]
Wait... All `appendixes` are named "Appendix"? I thought they were supposed to be "Annex"es...

ping @opoudjis

**Comment by opoudjis** [comment]
In fact, yes they are: 

````
      def i18n_init(lang, script)
        super
        @annex_lbl = "Appendix"
      end
````

For me to have done this, I would have been told to do this for CSD. I will remove it only if you confirm that I must.

**Comment by ronaldtse** [comment]
Whoa. 

Is there any meaningful difference between “annex” and “appendix”? Can an “appendix” be normative? “Annex” means part of the content?

**Comment by opoudjis** [comment]
I do not believe there is a meaningful difference, though you're the one that works with standards bodies. For me to have done this, I will have been told that CalConnect uses "Appendix" instead of "Annex"; that's something for you to go back and verify with CalConnect. If there is an Appendix/Annex differentiation they make along normative/informative lines, that will be some extra work. Then again, I have my doubts that they would do that: it would be just confusing.

**Comment by opoudjis** [comment]
@ronaldtse Please indicate whether there is anything for me to do here.

**Comment by ronaldtse** [comment]
Let's keep "Appendix" for now. Not changing unless necessary.
